name: Tests
on: [push]

jobs:
  test:
    - name: Prepare java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@2.0
    - name: Run tests
      run: lein test :all
