name: Tests
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Clojure deps cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.deps.clj
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Clojure Tooling
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          bb: 'latest'

      - name: Tools versions
        run: |
          echo "bb --version"
          bb --version
          echo "java -version"
          java -version

      - name: Bring down deps
        run: bb deps

      - name: Lint
        run: bb lint

  test-jvm:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows"]
        clojure-version: ["1.8", "1.9", "1.10", "1.11"]
        java-version: ["8", "11", "17"]

    name: ${{ matrix.os }} clj-${{ matrix.clojure-version }} jdk${{ matrix.java-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Clojure deps cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.deps.clj
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      - name: Setup Clojure Tooling
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          bb: 'latest'

      - name: Tools versions
        run: |
          echo "bb --version"
          bb --version
          echo "java -version"
          java -version

      - name: Bring down deps
        run: bb deps

      - name: Run tests
        run: bb test:jvm --clj-version ${{ matrix.clojure-version }}

  test-bb:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows"]

    name: ${{ matrix.os }} bb

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Clojure deps cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.deps.clj
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '17'

      - name: Setup Clojure Tooling
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          bb: 'latest'

      - name: Tools versions
        run: |
          echo "bb --version"
          bb --version
          echo "java -version"
          java -version

      - name: Run tests
        run: bb test:bb

  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test-jvm
      - test-bb

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Clojure deps cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.deps.clj
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Clojure Tooling
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          bb: 'latest'
          cli: 'latest'

      - name: Tools versions
        run: |
          echo "bb --version"
          bb --version
          echo "clojure --version"
          clojure --version
          echo "java -version"
          java -version

      - name: Bring down deps
        run: bb deps

      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -T:build maybe-deploy
