name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clojure-version: ["1.8", "1.9", "1.10"]
        java-version: ["8", "11", "16"]
    steps:
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java-version }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          cli: 'latest'
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Run tests
        run: clojure -M:${{ matrix.clojure-version }}:test
  bb-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.3.0
        with:
          babashka-version: 0.6.4

      - name: tests
        run: bb test:bb
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - bb-test
    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v2-beta
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.10.3.1029 # Clojure CLI based on tools.deps
      - name: Deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -T:build maybe-deploy
